# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(810, 1266)
        window.setStyleSheet("")
        self.tabWidget = QtWidgets.QTabWidget(window)
        self.tabWidget.setGeometry(QtCore.QRect(50, 190, 701, 991))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabWidget::pane{\n"
"min-width:70px;\n"
"min-height:25px;\n"
"border-top: 2px solid;\n"
"border-top-color:rgb(85, 224, 255);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"\n"
"min-width:70px;\n"
"\n"
"min-height:25px;\n"
"\n"
"color:rgb(60, 140, 180);\n"
"\n"
"font:20px \"Microsoft YaHei\";\n"
"\n"
"border: 0px solid;\n"
"padding-left: 20px; /* 向右移动 20 像素 */\n"
"\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"\n"
"min-width:70px;\n"
"\n"
"min-height:25px;\n"
"color:rgb(85, 224, 255);\n"
"\n"
"font:22px \"Microsoft YaHei\";\n"
"\n"
"border: 0px solid;\n"
"\n"
"/* border-bottom: 2px solid;*/\n"
"\n"
"border-color: #4796f0;\n"
"\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setGeometry(QtCore.QRect(30, 650, 651, 31))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"border: 2px solid rgb(85, 224, 255);\n"
"border-radius: 10px;\n"
"background-color: white;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"background-color: rgb(85, 224, 255);\n"
"width: 20px;\n"
"}什么意思")
        self.progressBar.setProperty("value", 100)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(30, 40, 651, 591))
        self.groupBox.setStyleSheet("\n"
"\n"
"QGroupBox {\n"
"\n"
"    border: 2px solid rgb(85, 224, 255);\n"
"    border-radius: 10px;\n"
"    font-size: 25px; \n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    color: rgb(85, 224, 255); /* 设置标题的颜色为蓝色 */\n"
"\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.label_camera = QtWidgets.QLabel(self.groupBox)
        self.label_camera.setGeometry(QtCore.QRect(41, 34, 581, 521))
        self.label_camera.setStyleSheet("QLabel {\n"
"border: 2px solid rgb(85, 224, 255);\n"
"\n"
"background-color: white;\n"
"}")
        self.label_camera.setText("")
        self.label_camera.setObjectName("label_camera")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 740, 651, 181))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"\n"
"    border: 2px solid rgb(85, 224, 255);\n"
"    border-radius: 10px;\n"
"    font-size: 25px; \n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    color: rgb(85, 224, 255); /* 设置标题的颜色为蓝色 */\n"
"\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_recg_userimg = QtWidgets.QLabel(self.groupBox_2)
        self.label_recg_userimg.setGeometry(QtCore.QRect(90, 20, 141, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_recg_userimg.sizePolicy().hasHeightForWidth())
        self.label_recg_userimg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_recg_userimg.setFont(font)
        self.label_recg_userimg.setStyleSheet("color:rgb(85, 224, 255)")
        self.label_recg_userimg.setText("")
        self.label_recg_userimg.setPixmap(QtGui.QPixmap("src/noperson.png"))
        self.label_recg_userimg.setScaledContents(True)
        self.label_recg_userimg.setAlignment(QtCore.Qt.AlignCenter)
        self.label_recg_userimg.setObjectName("label_recg_userimg")
        self.label_recg_username = QtWidgets.QLabel(self.groupBox_2)
        self.label_recg_username.setGeometry(QtCore.QRect(330, 30, 261, 131))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_recg_username.setFont(font)
        self.label_recg_username.setStyleSheet("color:rgb(85, 224, 255)")
        self.label_recg_username.setAlignment(QtCore.Qt.AlignCenter)
        self.label_recg_username.setObjectName("label_recg_username")
        self.label_statu = QtWidgets.QLabel(self.tab)
        self.label_statu.setGeometry(QtCore.QRect(190, 690, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_statu.setFont(font)
        self.label_statu.setStyleSheet("color:rgb(85, 224, 255)")
        self.label_statu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_statu.setObjectName("label_statu")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 50, 681, 901))
        self.tabWidget_2.setStyleSheet("QTabWidget::pane{\n"
"min-width:70px;\n"
"min-height:25px;\n"
"border-top: 2px solid;\n"
"border-top-color:rgb(85, 224, 255);\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"\n"
"min-width:70px;\n"
"\n"
"min-height:25px;\n"
"\n"
"color:rgb(60, 140, 180);\n"
"\n"
"font:16px \"Microsoft YaHei\";\n"
"\n"
"border: 0px solid;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"\n"
"min-width:70px;\n"
"\n"
"min-height:25px;\n"
"color:rgb(85, 224, 255);\n"
"\n"
"font:18px \"Microsoft YaHei\";\n"
"\n"
"border: 0px solid;\n"
"\n"
"/*border-bottom: 2px solid;*/\n"
"\n"
"border-color: #4796f0;\n"
"\n"
"}")
        self.tabWidget_2.setUsesScrollButtons(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 60, 661, 361))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"\n"
"    border: 2px solid rgb(85, 224, 255);\n"
"    border-radius: 20px;\n"
"    font-size: 25px; \n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    color: rgb(85, 224, 255); /* 设置标题的颜色为蓝色 */\n"
"\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_registeduser = QtWidgets.QLabel(self.groupBox_3)
        self.label_registeduser.setGeometry(QtCore.QRect(40, 60, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_registeduser.setFont(font)
        self.label_registeduser.setStyleSheet("color :rgb(85, 224, 255)")
        self.label_registeduser.setObjectName("label_registeduser")
        self.comboBox_user = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_user.setEnabled(True)
        self.comboBox_user.setGeometry(QtCore.QRect(160, 60, 171, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_user.sizePolicy().hasHeightForWidth())
        self.comboBox_user.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.comboBox_user.setFont(font)
        self.comboBox_user.setStyleSheet("/* 设置边框样式 */\n"
"QComboBox {\n"
"    border: 2px solid #000000; /* 设置边框宽度和颜色 */\n"
"    border-radius: 10px; /* 设置边框圆角 */\n"
"    color:rgb(85, 224, 255);\n"
"}\n"
"\n"
"/* 设置下拉箭头样式 */\n"
"QComboBox::drop-down {\n"
"    width: 30px; /* 设置箭头宽度 */\n"
"    height: 38px; /* 设置箭头高度 */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"/* 设置下拉列表样式 */\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid #000000; /* 设置下拉列表边框样式 */\n"
"    border-radius: 10px; /* 设置下拉列表边框圆角 */\n"
"    background-color: #ffffff; /* 设置下拉列表背景颜色 */\n"
"}\n"
"\n"
"/* 设置下拉列表中的项样式 */\n"
"QComboBox QAbstractItemView::item {\n"
"    height: 30px; /* 设置项高度 */\n"
"    color: #000000; /* 设置项文字颜色 */\n"
"    border: 2px solid #000000; /* 设置下拉列表边框样式 */\n"
"    border-radius: 10px; /* 设置下拉列表边框圆角 */\n"
"}\n"
"\n"
"/* 设置下拉列表中的项鼠标悬停样式 */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #cccccc; /* 设置鼠标悬停时的背景颜色 */\n"
"}\n"
"\n"
"/* 设置下拉列表中的选中项样式 */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #ff0000; /* 设置选中项的背景颜色 */\n"
"    color: #ffffff; /* 设置选中项的文字颜色 */\n"
"}")
        self.comboBox_user.setObjectName("comboBox_user")
        self.comboBox_user.addItem("")
        self.label_regi_username = QtWidgets.QLabel(self.groupBox_3)
        self.label_regi_username.setGeometry(QtCore.QRect(30, 140, 101, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_regi_username.setFont(font)
        self.label_regi_username.setStyleSheet("color :rgb(85, 224, 255)")
        self.label_regi_username.setObjectName("label_regi_username")
        self.lineEdit_username = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_username.setGeometry(QtCore.QRect(160, 150, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setStyleSheet("border-radius: 10px;\n"
"color :rgb(85, 224, 255)")
        self.lineEdit_username.setPlaceholderText("")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.pushButton_del_user = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_del_user.setGeometry(QtCore.QRect(180, 280, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_del_user.setFont(font)
        self.pushButton_del_user.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(255,255,255);\n"
"    background-color: rgb(85, 224, 255);\n"
"    border-radius: 10px;\n"
"}/*\n"
"QPushButton:hover \n"
"{\n"
"    background-color: rgb(127,122,117)\n"
"}*/\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(33,30,27);\n"
"}")
        self.pushButton_del_user.setObjectName("pushButton_del_user")
        self.pushButton_regist = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_regist.setGeometry(QtCore.QRect(340, 280, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_regist.setFont(font)
        self.pushButton_regist.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(255,255,255);\n"
"    background-color: rgb(85, 224, 255);\n"
"    border-radius: 10px;\n"
"}/*\n"
"QPushButton:hover \n"
"{\n"
"    background-color: rgb(127,122,117)\n"
"}*/\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(33,30,27);\n"
"}")
        self.pushButton_regist.setObjectName("pushButton_regist")
        self.label_regi_userimg = QtWidgets.QLabel(self.groupBox_3)
        self.label_regi_userimg.setGeometry(QtCore.QRect(430, 30, 201, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_regi_userimg.sizePolicy().hasHeightForWidth())
        self.label_regi_userimg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_regi_userimg.setFont(font)
        self.label_regi_userimg.setStyleSheet("color :rgb(85, 224, 255)")
        self.label_regi_userimg.setText("")
        self.label_regi_userimg.setPixmap(QtGui.QPixmap("src/noperson.png"))
        self.label_regi_userimg.setScaledContents(True)
        self.label_regi_userimg.setAlignment(QtCore.Qt.AlignCenter)
        self.label_regi_userimg.setObjectName("label_regi_userimg")
        self.pushButton_loadimg = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_loadimg.setGeometry(QtCore.QRect(20, 280, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_loadimg.setFont(font)
        self.pushButton_loadimg.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(255,255,255);\n"
"    background-color: rgb(85, 224, 255);\n"
"    border-radius: 10px;\n"
"}/*\n"
"QPushButton:hover \n"
"{\n"
"    background-color: rgb(127,122,117)\n"
"}*/\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(33,30,27);\n"
"}")
        self.pushButton_loadimg.setObjectName("pushButton_loadimg")
        self.pushButton_del_info = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_del_info.setGeometry(QtCore.QRect(500, 280, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_del_info.setFont(font)
        self.pushButton_del_info.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(255,255,255);\n"
"    background-color: rgb(85, 224, 255);\n"
"    border-radius: 10px;\n"
"}/*\n"
"QPushButton:hover \n"
"{\n"
"    background-color: rgb(127,122,117)\n"
"}*/\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(33,30,27);\n"
"}")
        self.pushButton_del_info.setObjectName("pushButton_del_info")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_sim_label = QtWidgets.QLabel(self.tab_4)
        self.label_sim_label.setGeometry(QtCore.QRect(20, 40, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_sim_label.setFont(font)
        self.label_sim_label.setStyleSheet("color:rgb(85, 224, 255)")
        self.label_sim_label.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sim_label.setObjectName("label_sim_label")
        self.sim_horizontalSlider = QtWidgets.QSlider(self.tab_4)
        self.sim_horizontalSlider.setGeometry(QtCore.QRect(40, 100, 581, 22))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.sim_horizontalSlider.setFont(font)
        self.sim_horizontalSlider.setMouseTracking(False)
        self.sim_horizontalSlider.setAutoFillBackground(False)
        self.sim_horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"border: 3px solid rgb(85, 224, 255);\n"
"border-radius: 10px;\n"
"height: 20px;\n"
"background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(85, 224, 255), stop:1 white);\n"
"margin: 2px 0;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #45ADED, stop:1 #0080FF);\n"
"border: 1px solid rgb(85, 224, 255);\n"
"width: 18px;\n"
"margin: -2px 0;\n"
"border-radius: 5px;\n"
"}")
        self.sim_horizontalSlider.setMinimum(0)
        self.sim_horizontalSlider.setMaximum(100)
        self.sim_horizontalSlider.setSingleStep(1)
        self.sim_horizontalSlider.setProperty("value", 20)
        self.sim_horizontalSlider.setTracking(False)
        self.sim_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sim_horizontalSlider.setInvertedAppearance(False)
        self.sim_horizontalSlider.setObjectName("sim_horizontalSlider")
        self.label_sim_label_value = QtWidgets.QLabel(self.tab_4)
        self.label_sim_label_value.setGeometry(QtCore.QRect(630, 90, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_sim_label_value.setFont(font)
        self.label_sim_label_value.setStyleSheet("color:rgb(85, 224, 255)")
        self.label_sim_label_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sim_label_value.setObjectName("label_sim_label_value")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(50, 160, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(85, 224, 255)")
        self.label_3.setObjectName("label_3")
        self.spinBox_light = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_light.setGeometry(QtCore.QRect(180, 160, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.spinBox_light.setFont(font)
        self.spinBox_light.setStyleSheet("\n"
"    border: 2px solid rgb(85, 224, 255); /* 设置边框宽度和颜色 */\n"
"    border-radius: 10px; /* 设置边框圆角 */\n"
"    color:rgb(85, 224, 255);\n"
"")
        self.spinBox_light.setMinimum(-50)
        self.spinBox_light.setMaximum(50)
        self.spinBox_light.setObjectName("spinBox_light")
        self.pushButton_quit = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_quit.setGeometry(QtCore.QRect(500, 280, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setStyleSheet("QPushButton \n"
"{\n"
"    color: rgb(255,255,255);\n"
"    background-color: rgb(85, 224, 255);\n"
"    border-radius: 10px;\n"
"}/*\n"
"QPushButton:hover \n"
"{\n"
"    background-color: rgb(127,122,117)\n"
"}*/\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(33,30,27);\n"
"}")
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_titel = QtWidgets.QLabel(window)
        self.label_titel.setGeometry(QtCore.QRect(310, 50, 201, 91))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_titel.setFont(font)
        self.label_titel.setStyleSheet("color:rgb(85, 224, 255)")
        self.label_titel.setObjectName("label_titel")
        self.label_background = QtWidgets.QLabel(window)
        self.label_background.setGeometry(QtCore.QRect(-30, -70, 871, 1411))
        self.label_background.setText("")
        self.label_background.setPixmap(QtGui.QPixmap("src/backgroundnew.png"))
        self.label_background.setScaledContents(True)
        self.label_background.setObjectName("label_background")
        self.label_notion = QtWidgets.QLabel(window)
        self.label_notion.setGeometry(QtCore.QRect(70, 1180, 661, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_notion.sizePolicy().hasHeightForWidth())
        self.label_notion.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_notion.setFont(font)
        self.label_notion.setStyleSheet("color:rgb(85, 224, 255)")
        self.label_notion.setAlignment(QtCore.Qt.AlignCenter)
        self.label_notion.setObjectName("label_notion")
        self.label_scut = QtWidgets.QLabel(window)
        self.label_scut.setGeometry(QtCore.QRect(20, 10, 161, 161))
        self.label_scut.setText("")
        self.label_scut.setPixmap(QtGui.QPixmap("src/scut.png"))
        self.label_scut.setScaledContents(True)
        self.label_scut.setObjectName("label_scut")
        self.label_bip = QtWidgets.QLabel(window)
        self.label_bip.setGeometry(QtCore.QRect(610, 10, 171, 171))
        self.label_bip.setText("")
        self.label_bip.setPixmap(QtGui.QPixmap("src/biplab.png"))
        self.label_bip.setScaledContents(True)
        self.label_bip.setObjectName("label_bip")
        self.label_background.raise_()
        self.tabWidget.raise_()
        self.label_titel.raise_()
        self.label_notion.raise_()
        self.label_scut.raise_()
        self.label_bip.raise_()

        self.retranslateUi(window)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Form"))
        self.groupBox.setTitle(_translate("window", "摄像头"))
        self.groupBox_2.setTitle(_translate("window", "认证"))
        self.label_recg_username.setText(_translate("window", "认证用户信息"))
        self.label_statu.setText(_translate("window", "视频采集中"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("window", "认证"))
        self.groupBox_3.setTitle(_translate("window", "注册"))
        self.label_registeduser.setText(_translate("window", "已有用户："))
        self.comboBox_user.setItemText(0, _translate("window", "用户列表"))
        self.label_regi_username.setText(_translate("window", "用户名："))
        self.pushButton_del_user.setText(_translate("window", "删除用户"))
        self.pushButton_regist.setText(_translate("window", "注册用户"))
        self.pushButton_loadimg.setText(_translate("window", "加载头像"))
        self.pushButton_del_info.setText(_translate("window", "删除信息"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("window", "用户"))
        self.label_sim_label.setText(_translate("window", "相似度阈值："))
        self.label_sim_label_value.setText(_translate("window", "0.4"))
        self.label_3.setText(_translate("window", "背景光强："))
        self.pushButton_quit.setText(_translate("window", "退出系统"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("window", "设置"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("window", "日志"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("window", "管理"))
        self.label_titel.setText(_translate("window", "手势认证"))
        self.label_notion.setText(_translate("window", "↓↓↓请在下方执行手势↓↓↓"))
